-- ---------------------------------------------------------
-- Init PDB 
--Lưu ý cần đổi FILE_NAME_CONVERT cho phù hợp trên máy để chạy local
-- ---------------------------------------------------------

conn sys/123@localhost:1521/FREE as sysdba;
-- Chuyển về CDB$ROOT trước khi xóa PDB
ALTER SESSION SET CONTAINER = CDB$ROOT;

-- Xóa PDB nếu có
BEGIN
    EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE PDB CLOSE IMMEDIATE';
EXCEPTION
    WHEN OTHERS THEN NULL; -- Bỏ qua nếu PDB không tồn tại
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PLUGGABLE DATABASE PDB INCLUDING DATAFILES';
EXCEPTION
    WHEN OTHERS THEN NULL; -- Bỏ qua nếu PDB không tồn tại
END;
/

-- Tạo PDB
CREATE PLUGGABLE DATABASE PDB
  ADMIN USER AdminPdb IDENTIFIED BY 123
  ROLES = (DBA)
  FILE_NAME_CONVERT = (
    'C:\APP\ADMIN\PRODUCT\23AI\ORADATA\FREE\PDBSEED\', 
    'C:\APP\ADMIN\PRODUCT\23AI\ORADATA\FREE\PDB\'
);

-- Mở PDB nếu chưa mở 
CREATE OR REPLACE PROCEDURE Open_PDB_If_Closed(p_pdb_name IN VARCHAR2) 
IS
    v_open_mode VARCHAR2(20);
BEGIN
    SELECT open_mode INTO v_open_mode
    FROM v$pdbs
    WHERE name = UPPER(p_pdb_name);

    IF v_open_mode != 'READ WRITE' THEN
        EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE ' || p_pdb_name || ' OPEN';
        DBMS_OUTPUT.PUT_LINE('PDB ' || p_pdb_name || ' đã được mở.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('PDB ' || p_pdb_name || ' đã mở sẵn.');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Không tìm thấy PDB tên: ' || p_pdb_name);
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Lỗi: ' || SQLERRM);
END;
/
EXECUTE Open_PDB_If_Closed('PDB');
/

-- Kết nối vào PDB
ALTER SESSION SET CONTAINER = PDB;

-- Cấp quota cho AdminPdb trên tablespace SYSTEM
ALTER USER AdminPdb QUOTA UNLIMITED ON SYSTEM;

-- Cấp quyền cho AdminPdb
GRANT EXECUTE ON DBMS_FGA TO AdminPdb;
GRANT SELECT ON DBA_FGA_AUDIT_TRAIL TO AdminPdb;

conn AdminPdb/123@localhost:1521/PDB;
SET NLS_LANG=AMERICAN_AMERICA.AL32UTF8;

-- Bảng DONVI
CREATE TABLE DONVI (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV VARCHAR2(100),
    LOAIDV VARCHAR2(20),
    TRGDV VARCHAR2(10) 
);
-- MADV: HOA => TENDV: Khoa hoá học => LOAIDV: KHOA
-- MADV PDT => TENDV: Phòng đào tạo => LOAIDV: PHONG

-- Bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANLD VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    PHAI CHAR(1), -- 1: male, 0: female
    NGSINH DATE,
    LUONG NUMBER, 
    PHUCAP NUMBER,
    DT VARCHAR2(15),
    VAITRO VARCHAR2(50),
    MADV VARCHAR2(10), 
    FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);
ALTER TABLE DONVI ADD FOREIGN KEY (TRGDV) REFERENCES NHANVIEN(MANLD);
ALTER TABLE NHANVIEN ADD CONSTRAINT CS_NHANVIEN_PHAI CHECK (PHAI IN ('1', '0'));
-- NHANVIEN: VAITRO
-- NVCB: 500
-- GV: 200
-- NVPDT: 20
-- NVPKT: 10
-- NVTCHC: 15
-- NVPCTSV: 10
-- TRGDV: 15

-- Bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MASV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    PHAI CHAR(1),
    NGSINH DATE,
    DCHI VARCHAR2(256), 
    DT VARCHAR2(15),
    KHOA VARCHAR2(10),
    TINHTRANG VARCHAR2(100)
);
ALTER TABLE SINHVIEN ADD CONSTRAINT CS_SINHVIEN_PHAI CHECK (PHAI IN ('1', '0'));
-- NHANVIEN: 4000
ALTER TABLE SINHVIEN
MODIFY TINHTRANG VARCHAR2(100);

-- Bảng HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP VARCHAR2(100),
    SOTC NUMBER,
    STLT NUMBER,
    STTH NUMBER,
    MADV VARCHAR2(10),
    FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

-- Bảng MOMON
CREATE TABLE MOMON (
    MAMM VARCHAR2(20) PRIMARY KEY,
    MAHP VARCHAR2(10),
    MAGV VARCHAR2(10),
    HK NUMBER,
    NAM NUMBER,
    FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP),
    FOREIGN KEY (MAGV) REFERENCES NHANVIEN(MANLD)
);

-- Bảng DANGKY
CREATE TABLE DANGKY (
    MASV VARCHAR2(20),
    MAMM VARCHAR2(20),
    DIEMTH NUMBER,
    DIEMQT NUMBER,
    DIEMCK NUMBER,
    DIEMTK NUMBER,
    PRIMARY KEY (MASV, MAMM),
    FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    FOREIGN KEY (MAMM) REFERENCES MOMON(MAMM)
);
-- DIEMTK: => DIEMQT*20% + DIEMTH*30% + DIEMCK*50%


INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('TCHC', 'Phòng tổ chức hành chính', 'PHONG');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('PDT', 'Phòng đào tạo', 'PHONG');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('PKT', 'Phòng kế toán', 'PHONG');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('PCTSV', 'Phòng công tác sinh viên', 'PHONG');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('TOAN', 'Khoa Toán học', 'KHOA');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('VATLY', 'Khoa Vật lý', 'KHOA');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('CNTT', 'Khoa Công nghệ thông tin', 'KHOA');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('HOA', 'Khoa Hoá học', 'KHOA');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('KHKT', 'Khoa kỹ thuật', 'KHOA');  
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('SINH', 'Khoa Sinh học', 'KHOA');
-- SINHVIEN
-- NVCB
DECLARE
  ho  SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST(
    'Nguyễn', 'Trần', 'Lê', 'Phạm', 'Hoàng', 'Võ', 'Đặng', 'Bùi', 'Đỗ', 'Hồ'
  );
  ten SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST(
    'An', 'Bình', 'Chi', 'Dũng', 'Hùng', 'Mai', 'Lan', 'Hương', 'Minh', 'Thảo', 'Nam', 'Khoa', 'Hải', 'Tâm', 'Thắng'
  );
BEGIN
  FOR i IN 300..799 LOOP
    INSERT INTO NHANVIEN (
      MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV
    ) VALUES (
      'NV' || LPAD(i, 5, '0'),
      ho(MOD(i, ho.COUNT) + 1) || ' ' || ten(MOD(i, ten.COUNT) + 1),
      CASE MOD(i, 2) WHEN 0 THEN '1' ELSE '0' END,
      TO_DATE('1985-01-01', 'YYYY-MM-DD') + MOD(i, 7000),
      4000000 + MOD(i * 1111, 8000000),
      500000 + MOD(i * 2222, 3000000),
      '091' || TO_CHAR(1000000 + i),
      'NVCB',
      CASE 
        WHEN MOD(i, 6) = 0 THEN 'TOAN'
        WHEN MOD(i, 6) = 1 THEN 'CNTT'
        WHEN MOD(i, 6) = 2 THEN 'VATLY'
        WHEN MOD(i, 6) = 3 THEN 'SINH'
        WHEN MOD(i, 6) = 4 THEN 'HOA'
        ELSE 'KHKT'
      END
    );
  END LOOP;
  COMMIT;
END;
/
-- GV
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00001', 'Nguyễn Văn Tèo', '1', TO_DATE('1994-11-01', 'YYYY-MM-DD'), 5000000, 1000000, '0123456789', 'GV', 'TOAN');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00002', 'Nguyễn Văn Tí', '1', TO_DATE('1993-04-02', 'YYYY-MM-DD'), 6000000, 2000000, '0123456799', 'GV', 'VATLY');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00003', 'Nguyễn Văn Mai', '0', TO_DATE('2000-09-11', 'YYYY-MM-DD'), 6700000, 3000000, '0123456989', 'GV', 'SINH');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00004', 'Gia Cát Lượng', '1', TO_DATE('2002-03-01', 'YYYY-MM-DD'), 9000000, 2500000, '0123459789', 'GV', 'CNTT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00005', 'Trương Thị Thuý Kiều', '0', TO_DATE('2004-12-01', 'YYYY-MM-DD'), 5000000, 4000000, '0123496789', 'GV', 'TOAN');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00006', 'Tần Thuỷ Hoàng', '1', TO_DATE('1987-05-05', 'YYYY-MM-DD'), 50000000, 10000000, '0123956789', 'GV', 'VATLY');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00007', 'Hán Vũ Đế', '1', TO_DATE('1999-05-25', 'YYYY-MM-DD'), 4000000, 1000000, '0129456789', 'GV', 'SINH');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00008', 'Khang Hi', '1', TO_DATE('1998-06-26', 'YYYY-MM-DD'), 13000000, 1200000, '0193456789', 'GV', 'VATLY');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00009', 'Càn Long', '1', TO_DATE('2001-07-01', 'YYYY-MM-DD'), 22000000, 4000000, '0923456789', 'GV', 'SINH');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00010', 'Khổng Tử', '1', TO_DATE('1980-07-15', 'YYYY-MM-DD'), 7000000, 1000000, '0993456789', 'GV', 'VATLY');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00011', 'Quan Vũ', '1', TO_DATE('1972-02-28', 'YYYY-MM-DD'), 9000000, 1000000, '0929456789', 'GV', 'TOAN');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00012', 'Triệu Tử Long', '1', TO_DATE('1975-10-10', 'YYYY-MM-DD'), 11000000, 500000, '0923956789', 'GV', 'CNTT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00013', 'Hà Nhân', '1', TO_DATE('1960-07-17', 'YYYY-MM-DD'), 13000000, 1500000, '0923496789', 'GV', 'CNTT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00014', 'Nam', '1', TO_DATE('1960-07-17', 'YYYY-MM-DD'), 13000000, 1500000, '0923496789', 'NVPKT', 'CNTT');

DECLARE
  ho  SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST('Nguyễn', 'Trần', 'Lê', 'Phạm', 'Hoàng');
  ten SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST('An', 'Bình', 'Chi', 'Dũng', 'Hùng', 'Mai', 'Lan', 'Hương');
BEGIN
  FOR i IN 100..299 LOOP
    INSERT INTO NHANVIEN (
      MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV
    ) VALUES (
      'NV' || LPAD(i, 5, '0'),
      ho(MOD(i, ho.COUNT) + 1) || ' ' || ten(MOD(i, ten.COUNT) + 1),
      CASE MOD(i, 2) WHEN 0 THEN '1' ELSE '0' END,
      TO_DATE('1990-01-01', 'YYYY-MM-DD') + MOD(i, 365),
      5000000 + MOD(i * 10000, 10000000),
      1000000 + MOD(i * 5000, 5000000),
      '090' || TO_CHAR(1000000 + i),
      'GV',
      CASE 
        WHEN MOD(i, 5) = 0 THEN 'TOAN'
        WHEN MOD(i, 5) = 1 THEN 'CNTT'
        WHEN MOD(i, 5) = 2 THEN 'VATLY'
        WHEN MOD(i, 5) = 3 THEN 'SINH'
        ELSE 'HOA'
      END
    );
  END LOOP;
  COMMIT;
END;
/

--NV PDT 
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00015', 'Lê Quý Đôn', '1', TO_DATE('1994-05-11', 'YYYY-MM-DD'), 30000000, 2000000, '0923456989', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00023', 'Nguyễn Thị Lan', '0', TO_DATE('1990-02-01', 'YYYY-MM-DD'), 18000000, 2000000, '0900000001', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00024', 'Phạm Văn Hùng', '1', TO_DATE('1991-03-11', 'YYYY-MM-DD'), 17500000, 1500000, '0900000002', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00025', 'Trần Thị Mai', '0', TO_DATE('1988-05-14', 'YYYY-MM-DD'), 19000000, 1800000, '0900000003', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00026', 'Lê Văn An', '1', TO_DATE('1989-07-07', 'YYYY-MM-DD'), 16000000, 1700000, '0900000004', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00027', 'Hoàng Thị Hạnh', '0', TO_DATE('1993-09-21', 'YYYY-MM-DD'), 15500000, 1400000, '0900000005', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00028', 'Đoàn Văn Bình', '1', TO_DATE('1987-12-12', 'YYYY-MM-DD'), 16500000, 1600000, '0900000006', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00029', 'Nguyễn Thị Bích', '0', TO_DATE('1992-11-19', 'YYYY-MM-DD'), 17500000, 1200000, '0900000007', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00030', 'Võ Minh Trí', '1', TO_DATE('1994-01-25', 'YYYY-MM-DD'), 18500000, 1500000, '0900000008', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00031', 'Lý Thị Huệ', '0', TO_DATE('1986-10-08', 'YYYY-MM-DD'), 17000000, 1300000, '0900000009', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00032', 'Trịnh Văn Cường', '1', TO_DATE('1985-06-05', 'YYYY-MM-DD'), 16000000, 1400000, '0900000010', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00033', 'Nguyễn Thị Dung', '0', TO_DATE('1991-04-04', 'YYYY-MM-DD'), 18000000, 1900000, '0900000011', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00034', 'Phan Văn Hòa', '1', TO_DATE('1989-08-18', 'YYYY-MM-DD'), 15000000, 1500000, '0900000012', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00035', 'Đinh Thị Lệ', '0', TO_DATE('1990-03-30', 'YYYY-MM-DD'), 17000000, 2000000, '0900000013', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00036', 'Tạ Văn Sơn', '1', TO_DATE('1988-01-01', 'YYYY-MM-DD'), 19000000, 1900000, '0900000014', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00037', 'Trần Thị Thanh', '0', TO_DATE('1993-06-16', 'YYYY-MM-DD'), 18000000, 1800000, '0900000015', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00038', 'Lương Văn Hải', '1', TO_DATE('1986-02-20', 'YYYY-MM-DD'), 16000000, 1500000, '0900000016', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00039', 'Bùi Thị Ngọc', '0', TO_DATE('1992-12-12', 'YYYY-MM-DD'), 17000000, 1700000, '0900000017', 'NVPDT', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00040', 'Vũ Văn Quang', '1', TO_DATE('1991-07-07', 'YYYY-MM-DD'), 16500000, 1800000, '0900000018', 'NVPDT', 'PDT');

-- NV PKT
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00016', 'Trưng Trắc', '0', TO_DATE('1990-12-25', 'YYYY-MM-DD'), 15000000, 2000000, '0923456799', 'NVPKT', 'PKT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00017', 'Trưng Nhị', '0', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 25000000, 2000000, '0993456799', 'NVPKT', 'PKT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00041', 'Nguyễn Văn Phú', '1', TO_DATE('1984-03-22', 'YYYY-MM-DD'), 16000000, 2000000, '0900000101', 'NVPKT', 'PKT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00042', 'Lê Thị Tuyết', '0', TO_DATE('1989-09-11', 'YYYY-MM-DD'), 17000000, 1900000, '0900000102', 'NVPKT', 'PKT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00043', 'Hoàng Văn Đức', '1', TO_DATE('1990-05-06', 'YYYY-MM-DD'), 16500000, 2000000, '0900000103', 'NVPKT', 'PKT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00044', 'Phạm Thị Yến', '0', TO_DATE('1988-08-19', 'YYYY-MM-DD'), 15000000, 2100000, '0900000104', 'NVPKT', 'PKT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00045', 'Đỗ Văn Tuấn', '1', TO_DATE('1991-11-01', 'YYYY-MM-DD'), 16000000, 1900000, '0900000105', 'NVPKT', 'PKT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00046', 'Trịnh Thị Hoa', '0', TO_DATE('1985-12-25', 'YYYY-MM-DD'), 17500000, 1700000, '0900000106', 'NVPKT', 'PKT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00047', 'Tống Văn Hòa', '1', TO_DATE('1983-04-14', 'YYYY-MM-DD'), 15500000, 1800000, '0900000107', 'NVPKT', 'PKT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00048', 'Đặng Thị Thắm', '0', TO_DATE('1986-07-30', 'YYYY-MM-DD'), 16800000, 2000000, '0900000108', 'NVPKT', 'PKT');

-- NV TCHC
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00018', 'Trần Hưng Đạo', '1', TO_DATE('1980-09-24', 'YYYY-MM-DD'), 15000000, 2000000, '0929456799', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00019', 'Đinh Bộ Lĩnh', '1', TO_DATE('1982-05-17', 'YYYY-MM-DD'), 25000000, 2000000, '0923956799', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00049', 'Phạm Minh Thắng', '1', TO_DATE('1985-02-13', 'YYYY-MM-DD'), 16000000, 1800000, '0900000201', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00050', 'Ngô Thị Cúc', '0', TO_DATE('1990-06-19', 'YYYY-MM-DD'), 16500000, 2000000, '0900000202', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00051', 'Trương Văn Lợi', '1', TO_DATE('1989-04-05', 'YYYY-MM-DD'), 15500000, 1900000, '0900000203', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00052', 'Lê Thị Thu Hà', '0', TO_DATE('1991-11-12', 'YYYY-MM-DD'), 17000000, 1700000, '0900000204', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00053', 'Đinh Văn Nam', '1', TO_DATE('1988-03-21', 'YYYY-MM-DD'), 16000000, 1600000, '0900000205', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00054', 'Trần Thị Kim Chi', '0', TO_DATE('1992-09-14', 'YYYY-MM-DD'), 15800000, 1500000, '0900000206', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00055', 'Nguyễn Văn Bình', '1', TO_DATE('1986-01-30', 'YYYY-MM-DD'), 16500000, 1800000, '0900000207', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00056', 'Phan Thị Hồng', '0', TO_DATE('1993-12-07', 'YYYY-MM-DD'), 16000000, 2000000, '0900000208', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00057', 'Bùi Văn Quý', '1', TO_DATE('1987-05-16', 'YYYY-MM-DD'), 17000000, 1700000, '0900000209', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00058', 'Lý Thị Ánh', '0', TO_DATE('1990-10-22', 'YYYY-MM-DD'), 16200000, 1600000, '0900000210', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00059', 'Hoàng Văn Dương', '1', TO_DATE('1985-06-03', 'YYYY-MM-DD'), 16800000, 1900000, '0900000211', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00060', 'Đặng Thị Thanh', '0', TO_DATE('1989-08-29', 'YYYY-MM-DD'), 15500000, 1700000, '0900000212', 'NVTCHC', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00061', 'Tô Văn Lực', '1', TO_DATE('1991-02-17', 'YYYY-MM-DD'), 15800000, 1800000, '0900000213', 'NVTCHC', 'TCHC');

-- NV PCTSV
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00020', 'Thuý Kiều', '0', TO_DATE('1992-01-01', 'YYYY-MM-DD'), 15000000, 2000000, '0923496799', 'NVPCTSV', 'PCTSV');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00021', 'Thuý Vân', '0', TO_DATE('1992-01-01', 'YYYY-MM-DD'), 25000000, 2000000, '0923459799', 'NVPCTSV', 'PCTSV');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00062', 'Nguyễn Thị Tươi', '0', TO_DATE('1990-07-09', 'YYYY-MM-DD'), 16000000, 1900000, '0900000301', 'NVPCTSV', 'PCTSV');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00063', 'Trần Văn Khôi', '1', TO_DATE('1988-10-15', 'YYYY-MM-DD'), 15500000, 1700000, '0900000302', 'NVPCTSV', 'PCTSV');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00064', 'Lê Thị Thúy', '0', TO_DATE('1991-03-27', 'YYYY-MM-DD'), 16500000, 1600000, '0900000303', 'NVPCTSV', 'PCTSV');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00065', 'Phạm Văn Long', '1', TO_DATE('1986-05-19', 'YYYY-MM-DD'), 15000000, 2000000, '0900000304', 'NVPCTSV', 'PCTSV');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00066', 'Hoàng Thị Tuyết', '0', TO_DATE('1993-01-12', 'YYYY-MM-DD'), 16000000, 1500000, '0900000305', 'NVPCTSV', 'PCTSV');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00067', 'Đỗ Văn Nghĩa', '1', TO_DATE('1987-11-11', 'YYYY-MM-DD'), 15800000, 1700000, '0900000306', 'NVPCTSV', 'PCTSV');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00068', 'Vũ Thị Hạnh', '0', TO_DATE('1992-04-04', 'YYYY-MM-DD'), 16500000, 1800000, '0900000307', 'NVPCTSV', 'PCTSV');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00069', 'Tạ Văn Hào', '1', TO_DATE('1989-06-25', 'YYYY-MM-DD'), 17000000, 1900000, '0900000308', 'NVPCTSV', 'PCTSV');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00070', 'Ngô Thị Hoa', '0', TO_DATE('1990-08-30', 'YYYY-MM-DD'), 16000000, 1600000, '0900000309', 'NVPCTSV', 'PCTSV');

-- TRGDV
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00022', 'Phạm Ngũ Lão', '1', TO_DATE('1950-04-14', 'YYYY-MM-DD'), 35000000, 5000000, '0923456999', 'TRGDV', 'TOAN');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00071', 'Trịnh Văn Thọ', '1', TO_DATE('1975-03-10', 'YYYY-MM-DD'), 28000000, 3000000, '0900000401', 'TRGDV', 'TCHC');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00072', 'Nguyễn Thị Thuận', '0', TO_DATE('1980-06-18', 'YYYY-MM-DD'), 27500000, 2500000, '0900000402', 'TRGDV', 'PDT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00073', 'Lê Văn Kiệt', '1', TO_DATE('1978-01-27', 'YYYY-MM-DD'), 26000000, 2800000, '0900000403', 'TRGDV', 'PKT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00074', 'Võ Thị Hiền', '0', TO_DATE('1981-09-05', 'YYYY-MM-DD'), 27000000, 2900000, '0900000404', 'TRGDV', 'PCTSV');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00075', 'Đỗ Văn Chiến', '1', TO_DATE('1979-02-14', 'YYYY-MM-DD'), 26500000, 2700000, '0900000405', 'TRGDV', 'CNTT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00076', 'Bùi Thị Nga', '0', TO_DATE('1983-12-03', 'YYYY-MM-DD'), 25000000, 2600000, '0900000406', 'TRGDV', 'VATLY');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00077', 'Phạm Văn Quân', '1', TO_DATE('1976-08-22', 'YYYY-MM-DD'), 25500000, 2500000, '0900000407', 'TRGDV', 'HOA');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00078', 'Hoàng Thị Liên', '0', TO_DATE('1982-11-09', 'YYYY-MM-DD'), 26000000, 2400000, '0900000408', 'TRGDV', 'KHKT');
INSERT INTO NHANVIEN(MANLD, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV) VALUES ('NV00079', 'Ngô Văn Tâm', '1', TO_DATE('1977-05-17', 'YYYY-MM-DD'), 27000000, 2900000, '0900000409', 'TRGDV', 'SINH');

-- DONVI: TRGDV
UPDATE DONVI SET TRGDV = 'NV00071' WHERE MADV = 'TCHC';
UPDATE DONVI SET TRGDV = 'NV00072' WHERE MADV = 'PDT';
UPDATE DONVI SET TRGDV = 'NV00073' WHERE MADV = 'PKT';
UPDATE DONVI SET TRGDV = 'NV00074' WHERE MADV = 'PCTSV';
UPDATE DONVI SET TRGDV = 'NV00022' WHERE MADV = 'TOAN'; 
UPDATE DONVI SET TRGDV = 'NV00076' WHERE MADV = 'VATLY';
UPDATE DONVI SET TRGDV = 'NV00075' WHERE MADV = 'CNTT';
UPDATE DONVI SET TRGDV = 'NV00077' WHERE MADV = 'HOA';
UPDATE DONVI SET TRGDV = 'NV00078' WHERE MADV = 'KHKT';
UPDATE DONVI SET TRGDV = 'NV00079' WHERE MADV = 'SINH';


-- HOCPHAN
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00003', 'Vi tích phân 1B', 3, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00081', 'Thực hành Vi tích phân 1B', 1, 0, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00004', 'Vi tích phân 2B', 3, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00082', 'Thực hành Vi tích phân 2B', 1, 0, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00030', 'Đại số tuyến tính', 3, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00083', 'Thực hành Đại số tuyến tính', 1, 0, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00040', 'Xác xuất thống kê', 3, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00085', 'Thực hành Xác xuất thống kê', 1, 0, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00041', 'Toán rời rạc', 3, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00086', 'Thực hành Toán rời rạc', 1, 0, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00050', 'Toán học tổ hợp', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00051', 'Toán ứng dụng và thống kê', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00052', 'Phương pháp tính', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00053', 'Lý thuyết số', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00054', 'Phép tính vị từ', 4, 45, 30, 'TOAN');


INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('PHY00001', 'Vật lý đại cương 1', 3, 30, 0, 'VATLY');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('PHY00002', 'Vật lý đại cương 2', 3, 30, 0, 'VATLY');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('PHY00081', 'Thực hành Vật lý đại cương 1', 2, 0, 60, 'VATLY');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('PHY00082', 'Thực hành Vật lý đại cương 2', 2, 0, 60, 'VATLY');

INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BIO00001', 'Sinh đại cương 1', 3, 30, 0, 'SINH');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BIO00002', 'Sinh đại cương 2', 3, 30, 0, 'SINH');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BIO00081', 'Thực hành Sinh đại cương 1', 2, 0, 60, 'SINH');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BIO00082', 'Thực hành Sinh đại cương 2', 2, 0, 60, 'SINH');

INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10001', 'Nhập môn lâp trình', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10002', 'Kỹ thuật lập trình', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10003', 'Phương pháp lập trình hướng đối tượng', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10004', 'Cấu trúc dữ liệu và giải thuật', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10006', 'Cơ sở dữ liệu', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10007', 'Hệ điều hành', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10008', 'Mạng máy tính', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10009', 'Hệ thống máy tính', 2, 30, 0, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC13002', 'Nhập môn công nghệ phần mềm', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC14003', 'Cơ sở trí tuệ nhân tạo', 4, 45, 30, 'CNTT');



INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC00004', 'Nhập môn công nghệ thông tin', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BAA00011', 'Anh văn 1', 3, 30, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BAA00012', 'Anh văn 2', 3, 30, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BAA00013', 'Anh văn 3', 3, 30, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BAA00014', 'Anh văn 4', 3, 30, 30, 'CNTT');



INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC12001', 'An toàn và bảo mật dữ liệu trong hệ thống thông tin', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC12002', 'Cơ sở dữ liệu nâng cao', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC12003', 'Hệ quản trị cơ sở dữ liệu', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC12004', 'Phân tích thiết kế hệ thống thông tin', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC12005', 'Phát triển ứng dụng hệ thống thông tin hiện đại', 4, 45, 30, 'CNTT');



INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH10404', 'Lý thuyết thống kê', 3, 15, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH10405', 'Cấu trúc dữ liệu và giải thuật', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH10406', 'Toán rời rạc', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH10407', 'Lập trình hướng đối tượng', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH10401', 'Lý thuyết độ đo và xác suất', 4, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH10402', 'Đại số A2', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH10403', 'Giải tích hàm', 4, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH11010', 'Phương pháp giảng dạy toán 1', 3, 30, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH11011', 'Phương pháp giảng dạy toán 2', 3, 30, 30, 'TOAN');


-- MOMON

-- Môn MTH00003 (Vi tích phân 1B)
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00003_1_2024', 'MTH00003', 'NV00001', 1, 2024);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00003_2_2024', 'MTH00003', 'NV00002', 2, 2024);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00003_3_2024', 'MTH00003', 'NV00003', 3, 2024);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00003_1_2025', 'MTH00003', 'NV00004', 1, 2025);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00003_2_2025', 'MTH00003', 'NV00005', 2, 2025);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00003_3_2025', 'MTH00003', 'NV00006', 3, 2025);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00003_1_2026', 'MTH00003', 'NV00007', 1, 2026);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00003_2_2026', 'MTH00003', 'NV00008', 2, 2026);

-- Môn MTH00081 (Thực hành Vi tích phân 1B)
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00081_1_2024', 'MTH00081', 'NV00009', 1, 2024);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00081_2_2024', 'MTH00081', 'NV00010', 2, 2024);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00081_3_2024', 'MTH00081', 'NV00011', 3, 2024);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00081_1_2025', 'MTH00081', 'NV00012', 1, 2025);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00081_2_2025', 'MTH00081', 'NV00013', 2, 2025);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00081_3_2025', 'MTH00081', 'NV00014', 3, 2025);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00081_1_2026', 'MTH00081', 'NV00015', 1, 2026);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('MTH00081_2_2026', 'MTH00081', 'NV00016', 2, 2026);

-- Môn CSC10001 (Nhập môn lập trình)
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('CSC10001_1_2024', 'CSC10001', 'NV00017', 1, 2024);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('CSC10001_2_2024', 'CSC10001', 'NV00018', 2, 2024);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('CSC10001_3_2024', 'CSC10001', 'NV00019', 3, 2024);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('CSC10001_1_2025', 'CSC10001', 'NV00020', 1, 2025);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('CSC10001_2_2025', 'CSC10001', 'NV00021', 2, 2025);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('CSC10001_3_2025', 'CSC10001', 'NV00022', 3, 2025);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('CSC10001_1_2026', 'CSC10001', 'NV00023', 1, 2026);
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) VALUES ('CSC10001_2_2026', 'CSC10001', 'NV00024', 2, 2026);

-- REM INSERTING into SINHVIEN
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A536166','Bùi Thị Dũng','0',to_date('02/09/03','DD/MM/RR'),'Q.1, TP.HCM','0243119698','CNTT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A864352','Hoàng Thị Phúc','1',to_date('23/10/05','DD/MM/RR'),'TP. Đà Nẵng','0855307196','VATLY','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A475349','Bùi Ngọc Dũng','0',to_date('01/08/00','DD/MM/RR'),'Q.10, TP.HCM','0721855380','VATLY','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A110584','Vũ Minh Nam','1',to_date('08/07/03','DD/MM/RR'),'Q.3, TP.HCM','0516666687','HOA','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A921624','Phạm Minh Dũng','1',to_date('05/02/05','DD/MM/RR'),'TP. Thủ Đức','0515056651','TOAN','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A355087','Phan Gia Hà','0',to_date('19/02/06','DD/MM/RR'),'TP. Hà Nội','0943604938','VATLY','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A135403','Hoàng Hữu Hương','0',to_date('21/06/00','DD/MM/RR'),'Q.10, TP.HCM','0199236171','HOA','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A178637','Phạm Gia Châu','1',to_date('28/09/04','DD/MM/RR'),'TP. Thủ Đức','0426663612','TOAN','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A483012','Hoàng Thị Hà','1',to_date('18/02/02','DD/MM/RR'),'Q.10, TP.HCM','0437445990','VATLY','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A269894','Phan Hữu Nam','0',to_date('02/06/03','DD/MM/RR'),'Q.5, TP.HCM','0393566050','KHKT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A226885','Lê Minh Khánh','0',to_date('13/01/07','DD/MM/RR'),'Q.10, TP.HCM','0747037143','HOA','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A353214','Lê Anh Dũng','1',to_date('26/11/06','DD/MM/RR'),'TP. Đà Nẵng','0837339503','SINH','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A136068','Vũ Minh Khánh','0',to_date('01/07/03','DD/MM/RR'),'TP. Cần Thơ','0248745173','TOAN','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A928456','Phạm Văn Bình','1',to_date('12/11/00','DD/MM/RR'),'Q.3, TP.HCM','0934658575','HOA','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A848927','Nguyễn Văn Phúc','1',to_date('09/10/05','DD/MM/RR'),'Q.1, TP.HCM','0944025116','KHKT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A592848','Hoàng Ngọc Trang','0',to_date('12/05/04','DD/MM/RR'),'TP. Hà Nội','0529332369','VATLY','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A264688','Hoàng Anh Châu','0',to_date('24/02/05','DD/MM/RR'),'Q.5, TP.HCM','0192240853','CNTT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A408938','Vũ Anh An','1',to_date('03/02/06','DD/MM/RR'),'Q.3, TP.HCM','0688031092','SINH','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A884050','Vũ Anh Khánh','0',to_date('24/07/01','DD/MM/RR'),'TP. Biên Hòa','0455319238','TOAN','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A426151','Bùi Ngọc Dũng','1',to_date('24/09/03','DD/MM/RR'),'TP. Đà Nẵng','0810757069','TOAN','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A126102','Lê Ngọc Dũng','1',to_date('13/09/05','DD/MM/RR'),'Q.3, TP.HCM','0709788629','VATLY','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A452616','Hoàng Gia Khánh','0',to_date('12/05/00','DD/MM/RR'),'TP. Vũng Tàu','0121803248','VATLY','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A688411','Phan Anh Hà','1',to_date('15/06/04','DD/MM/RR'),'TP. Thủ Đức','0793519947','SINH','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A996000','Bùi Hữu Hà','0',to_date('13/09/05','DD/MM/RR'),'TP. Đà Nẵng','0289597211','KHKT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A746642','Trần Văn Hương','0',to_date('23/12/06','DD/MM/RR'),'Q.3, TP.HCM','0953203146','SINH','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A350276','Hoàng Ngọc Nam','1',to_date('27/09/06','DD/MM/RR'),'TP. Biên Hòa','0996151818','VATLY','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A193373','Phan Gia Châu','1',to_date('27/12/02','DD/MM/RR'),'Q.10, TP.HCM','0839459822','KHKT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A304840','Lê Gia An','1',to_date('14/02/06','DD/MM/RR'),'TP. Cần Thơ','0513668990','VATLY','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A662618','Vũ Văn Linh','0',to_date('11/04/02','DD/MM/RR'),'Q.5, TP.HCM','0349026929','HOA','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A962787','Bùi Anh Hà','0',to_date('17/05/05','DD/MM/RR'),'Q.3, TP.HCM','0376161550','KHKT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A858099','Bùi Gia Linh','1',to_date('13/09/03','DD/MM/RR'),'TP. Hà Nội','0504506043','TOAN','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A879801','Bùi Thị Tú','0',to_date('31/01/05','DD/MM/RR'),'Q.3, TP.HCM','0341319572','TOAN','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A320934','Trần Ngọc Nam','1',to_date('27/05/06','DD/MM/RR'),'Q.3, TP.HCM','0711260367','VATLY','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A944169','Đặng Thị Phúc','0',to_date('15/03/01','DD/MM/RR'),'Q.1, TP.HCM','0725164468','VATLY','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A720196','Lê Văn Châu','0',to_date('26/09/05','DD/MM/RR'),'TP. Cần Thơ','0830556367','VATLY','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A273588','Phan Minh Tú','1',to_date('04/05/02','DD/MM/RR'),'TP. Cần Thơ','0879000782','SINH','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A171291','Hoàng Gia Hương','0',to_date('25/01/06','DD/MM/RR'),'Q.10, TP.HCM','0235010462','KHKT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A428312','Trần Gia Dũng','0',to_date('05/12/05','DD/MM/RR'),'TP. Thủ Đức','0378096457','HOA','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A661922','Lê Thị Phúc','1',to_date('21/06/03','DD/MM/RR'),'TP. Hà Nội','0102926227','HOA','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A736173','Phạm Thị Nam','1',to_date('03/07/04','DD/MM/RR'),'Q.10, TP.HCM','0853049419','HOA','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A712542','Đặng Ngọc Khánh','0',to_date('26/09/02','DD/MM/RR'),'Q.5, TP.HCM','0654905654','VATLY','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A957253','Đặng Hữu Dũng','1',to_date('07/08/02','DD/MM/RR'),'TP. Cần Thơ','0644592133','KHKT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A313462','Trần Gia Quân','0',to_date('13/07/01','DD/MM/RR'),'TP. Đà Nẵng','0708379025','HOA','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A658238','Vũ Anh Linh','0',to_date('08/09/00','DD/MM/RR'),'TP. Đà Nẵng','0158617967','CNTT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A462200','Đặng Anh Hà','0',to_date('08/02/02','DD/MM/RR'),'Q.10, TP.HCM','0891228357','HOA','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A311347','Phạm Ngọc Linh','0',to_date('26/02/04','DD/MM/RR'),'TP. Biên Hòa','0232842358','TOAN','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A708662','Nguyễn Gia Nam','1',to_date('10/11/06','DD/MM/RR'),'TP. Đà Nẵng','0245402686','TOAN','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A803408','Nguyễn Minh Tú','1',to_date('11/10/04','DD/MM/RR'),'Q.3, TP.HCM','0570982778','VATLY','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A969025','Bùi Hữu Bình','1',to_date('08/11/04','DD/MM/RR'),'TP. Biên Hòa','0971369851','VATLY','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A480598','Bùi Anh Hương','0',to_date('11/01/04','DD/MM/RR'),'TP. Thủ Đức','0923710655','TOAN','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A344064','Lê Hữu Nam','1',to_date('22/03/02','DD/MM/RR'),'TP. Biên Hòa','0813495764','TOAN','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A106475','Nguyễn Văn An','0',to_date('14/04/03','DD/MM/RR'),'TP. Đà Nẵng','0667827373','KHKT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A754483','Phan Anh Bình','1',to_date('05/04/05','DD/MM/RR'),'Q.3, TP.HCM','0239400023','SINH','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A251602','Hoàng Thị Nam','0',to_date('04/03/04','DD/MM/RR'),'Q.3, TP.HCM','0366937454','VATLY','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A701535','Đặng Hữu Linh','1',to_date('22/10/05','DD/MM/RR'),'TP. Biên Hòa','0547612259','VATLY','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A560593','Hoàng Minh Dũng','1',to_date('28/03/03','DD/MM/RR'),'Q.1, TP.HCM','0366277813','CNTT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A889566','Vũ Ngọc Dũng','0',to_date('19/03/05','DD/MM/RR'),'TP. Cần Thơ','0639585658','SINH','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A709942','Bùi Gia An','1',to_date('14/10/04','DD/MM/RR'),'TP. Thủ Đức','0727466310','HOA','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A270967','Vũ Thị Nam','1',to_date('12/07/01','DD/MM/RR'),'Q.1, TP.HCM','0445466817','HOA','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A679370','Phan Gia Nam','0',to_date('13/01/04','DD/MM/RR'),'TP. Cần Thơ','0507169609','SINH','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A283132','Bùi Hữu Khánh','0',to_date('03/10/04','DD/MM/RR'),'Q.3, TP.HCM','0983330661','TOAN','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A957106','Bùi Thị Châu','1',to_date('26/07/06','DD/MM/RR'),'TP. Đà Nẵng','0234114059','TOAN','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A291530','Hoàng Ngọc Vy','0',to_date('29/10/04','DD/MM/RR'),'TP. Cần Thơ','0789137283','KHKT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A607392','Vũ Hữu Vy','0',to_date('17/06/01','DD/MM/RR'),'Q.3, TP.HCM','0709814965','HOA','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A603756','Phan Anh Dũng','1',to_date('21/12/02','DD/MM/RR'),'Q.1, TP.HCM','0222710039','CNTT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A129065','Phan Anh Châu','1',to_date('08/10/02','DD/MM/RR'),'TP. Hà Nội','0207879336','VATLY','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A492271','Lê Văn Hà','0',to_date('14/11/04','DD/MM/RR'),'Q.3, TP.HCM','0259224140','HOA','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A546018','Đặng Minh Vy','1',to_date('21/09/05','DD/MM/RR'),'Q.10, TP.HCM','0450361967','KHKT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A319466','Nguyễn Thị Trang','1',to_date('20/08/00','DD/MM/RR'),'TP. Biên Hòa','0758113087','TOAN','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A224215','Đặng Gia Trang','1',to_date('19/04/00','DD/MM/RR'),'Q.1, TP.HCM','0413912442','HOA','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A355384','Phạm Gia Dũng','1',to_date('21/04/01','DD/MM/RR'),'TP. Biên Hòa','0766981911','KHKT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A209408','Vũ Ngọc Hà','1',to_date('11/09/02','DD/MM/RR'),'Q.1, TP.HCM','0880474471','VATLY','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A501489','Phan Thị Linh','1',to_date('11/03/06','DD/MM/RR'),'TP. Hà Nội','0188224715','SINH','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A776144','Hoàng Hữu An','0',to_date('13/02/01','DD/MM/RR'),'Q.10, TP.HCM','0271855215','HOA','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A664297','Lê Gia Hà','1',to_date('01/06/01','DD/MM/RR'),'TP. Cần Thơ','0450442661','HOA','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A452414','Bùi Anh Linh','0',to_date('02/02/05','DD/MM/RR'),'Q.1, TP.HCM','0654729138','TOAN','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A707874','Lê Thị Linh','1',to_date('13/02/01','DD/MM/RR'),'TP. Vũng Tàu','0202003141','SINH','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A782985','Nguyễn Văn Hương','0',to_date('18/06/03','DD/MM/RR'),'TP. Biên Hòa','0761558218','HOA','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A238247','Nguyễn Gia Dũng','0',to_date('20/12/05','DD/MM/RR'),'TP. Đà Nẵng','0125944343','HOA','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A565645','Bùi Văn Khánh','1',to_date('27/06/00','DD/MM/RR'),'TP. Thủ Đức','0578094473','CNTT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A593644','Nguyễn Văn Quân','1',to_date('16/09/04','DD/MM/RR'),'Q.5, TP.HCM','0826752243','KHKT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A658798','Trần Minh Hương','1',to_date('14/02/07','DD/MM/RR'),'TP. Biên Hòa','0220176021','VATLY','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A728108','Phạm Thị Hà','1',to_date('08/09/00','DD/MM/RR'),'Q.10, TP.HCM','0977380185','KHKT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A768318','Nguyễn Thị Phúc','1',to_date('24/05/05','DD/MM/RR'),'TP. Hà Nội','0327920377','TOAN','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A488686','Đặng Anh Tú','1',to_date('02/04/05','DD/MM/RR'),'Q.5, TP.HCM','0801811223','VATLY','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A101132','Nguyễn Văn Hà','0',to_date('19/06/01','DD/MM/RR'),'Q.3, TP.HCM','0796859633','VATLY','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A499847','Bùi Minh Hà','1',to_date('25/06/06','DD/MM/RR'),'TP. Đà Nẵng','0377687586','CNTT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A855679','Vũ Minh Dũng','1',to_date('24/04/05','DD/MM/RR'),'TP. Đà Nẵng','0159997715','CNTT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A172422','Vũ Hữu Nam','1',to_date('03/02/07','DD/MM/RR'),'Q.1, TP.HCM','0836425350','TOAN','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A346031','Hoàng Thị An','1',to_date('06/12/02','DD/MM/RR'),'TP. Hà Nội','0968351787','TOAN','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A636598','Trần Thị Nam','0',to_date('20/11/06','DD/MM/RR'),'TP. Biên Hòa','0557181390','CNTT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A568746','Bùi Văn Khánh','1',to_date('12/02/03','DD/MM/RR'),'TP. Cần Thơ','0192370318','VATLY','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A232316','Phạm Anh Vy','0',to_date('01/11/05','DD/MM/RR'),'Q.3, TP.HCM','0834359173','TOAN','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A332777','Vũ Hữu Châu','1',to_date('10/09/00','DD/MM/RR'),'Q.5, TP.HCM','0737108251','VATLY','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A892641','Trần Văn Phúc','1',to_date('05/02/04','DD/MM/RR'),'TP. Hà Nội','0138352557','HOA','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A137165','Vũ Ngọc Hương','0',to_date('23/07/01','DD/MM/RR'),'Q.10, TP.HCM','0917146618','CNTT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A991249','Trần Văn Linh','1',to_date('20/02/06','DD/MM/RR'),'Q.5, TP.HCM','0498546751','VATLY','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A143318','Vũ Văn Quân','1',to_date('21/04/06','DD/MM/RR'),'TP. Thủ Đức','0588826657','CNTT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A936345','Đặng Anh Khánh','1',to_date('09/02/04','DD/MM/RR'),'Q.1, TP.HCM','0635911480','CNTT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A421801','Đặng Văn Dũng','0',to_date('03/09/05','DD/MM/RR'),'TP. Cần Thơ','0384579827','HOA','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A454412','Trần Anh Hà','0',to_date('01/08/03','DD/MM/RR'),'Q.3, TP.HCM','0823528625','VATLY','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A624582','Hoàng Hữu Hương','1',to_date('29/11/05','DD/MM/RR'),'Q.10, TP.HCM','0863043879','CNTT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A339137','Phan Thị Hương','0',to_date('19/11/05','DD/MM/RR'),'Q.10, TP.HCM','0281635074','SINH','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A178758','Vũ Anh Vy','0',to_date('27/11/06','DD/MM/RR'),'TP. Cần Thơ','0737137621','CNTT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A552069','Hoàng Hữu Hà','1',to_date('24/10/06','DD/MM/RR'),'TP. Thủ Đức','0809996961','CNTT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A672845','Trần Thị Quân','1',to_date('12/05/03','DD/MM/RR'),'TP. Cần Thơ','0594950864','HOA','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A453401','Bùi Gia Quân','0',to_date('10/09/00','DD/MM/RR'),'Q.5, TP.HCM','0762408544','CNTT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A827448','Nguyễn Ngọc Trang','1',to_date('11/12/01','DD/MM/RR'),'TP. Đà Nẵng','0289830108','SINH','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A250874','Bùi Văn Hương','0',to_date('06/11/06','DD/MM/RR'),'Q.5, TP.HCM','0330631902','TOAN','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A974147','Phan Hữu Bình','1',to_date('03/02/01','DD/MM/RR'),'Q.10, TP.HCM','0157430123','HOA','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A402902','Lê Văn Bình','0',to_date('17/04/02','DD/MM/RR'),'TP. Biên Hòa','0834129739','SINH','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A424220','Đặng Ngọc Hương','1',to_date('11/01/06','DD/MM/RR'),'TP. Biên Hòa','0599450845','SINH','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A105874','Phạm Ngọc Hà','1',to_date('10/08/02','DD/MM/RR'),'Q.1, TP.HCM','0318888237','CNTT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A914741','Nguyễn Anh Quân','1',to_date('21/12/00','DD/MM/RR'),'TP. Hà Nội','0981276783','TOAN','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A382468','Phạm Ngọc Quân','0',to_date('13/03/02','DD/MM/RR'),'Q.10, TP.HCM','0233744504','KHKT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A139283','Trần Anh Trang','0',to_date('18/05/00','DD/MM/RR'),'Q.5, TP.HCM','0270988281','KHKT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A810190','Lê Hữu Châu','0',to_date('25/01/04','DD/MM/RR'),'TP. Đà Nẵng','0653850372','SINH','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A501203','Phạm Thị Quân','1',to_date('10/08/00','DD/MM/RR'),'Q.1, TP.HCM','0823382410','SINH','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A732545','Phạm Gia Vy','1',to_date('13/06/02','DD/MM/RR'),'Q.1, TP.HCM','0735905402','HOA','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A644147','Đặng Gia Dũng','0',to_date('03/06/03','DD/MM/RR'),'TP. Biên Hòa','0111527229','KHKT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A439317','Phan Hữu Tú','1',to_date('19/10/02','DD/MM/RR'),'TP. Đà Nẵng','0299133875','SINH','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A953333','Lê Ngọc Bình','0',to_date('25/08/05','DD/MM/RR'),'TP. Đà Nẵng','0652121818','KHKT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A695990','Phạm Văn Phúc','0',to_date('30/12/02','DD/MM/RR'),'Q.1, TP.HCM','0138728648','HOA','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A408719','Nguyễn Thị Trang','0',to_date('28/02/05','DD/MM/RR'),'Q.3, TP.HCM','0250464046','SINH','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A656732','Vũ Anh Vy','0',to_date('15/10/05','DD/MM/RR'),'TP. Hà Nội','0868980160','CNTT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A626787','Đặng Thị Tú','1',to_date('14/08/00','DD/MM/RR'),'TP. Cần Thơ','0848459292','SINH','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A165301','Đặng Hữu Khánh','1',to_date('10/04/02','DD/MM/RR'),'TP. Vũng Tàu','0743411848','VATLY','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A273400','Trần Văn Khánh','0',to_date('16/03/05','DD/MM/RR'),'Q.3, TP.HCM','0776692288','HOA','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A355151','Đặng Gia Trang','0',to_date('09/12/00','DD/MM/RR'),'TP. Biên Hòa','0745908878','TOAN','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A187549','Trần Thị Bình','1',to_date('25/06/06','DD/MM/RR'),'Q.10, TP.HCM','0623155620','CNTT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A704656','Bùi Anh Vy','0',to_date('03/01/04','DD/MM/RR'),'TP. Hà Nội','0551796981','HOA','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A342103','Lê Ngọc Phúc','1',to_date('12/11/06','DD/MM/RR'),'Q.5, TP.HCM','0402549835','TOAN','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A505299','Phạm Ngọc Châu','0',to_date('30/08/03','DD/MM/RR'),'TP. Thủ Đức','0520812507','TOAN','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A889877','Trần Gia An','1',to_date('25/02/06','DD/MM/RR'),'Q.5, TP.HCM','0126637022','KHKT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A853682','Nguyễn Anh Khánh','1',to_date('18/07/04','DD/MM/RR'),'TP. Thủ Đức','0668525655','KHKT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A209306','Phạm Minh Hà','1',to_date('28/11/04','DD/MM/RR'),'Q.1, TP.HCM','0197236612','CNTT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A127468','Hoàng Thị Tú','0',to_date('11/02/06','DD/MM/RR'),'Q.1, TP.HCM','0922314813','TOAN','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A169704','Phạm Gia Châu','0',to_date('08/12/01','DD/MM/RR'),'TP. Đà Nẵng','0916997182','CNTT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A376133','Trần Thị Hương','1',to_date('24/02/05','DD/MM/RR'),'TP. Biên Hòa','0184509769','VATLY','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A159841','Đặng Văn Khánh','1',to_date('25/09/02','DD/MM/RR'),'TP. Biên Hòa','0436588305','CNTT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A377633','Nguyễn Thị Linh','1',to_date('17/08/00','DD/MM/RR'),'TP. Vũng Tàu','0653807066','HOA','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A463512','Phạm Anh Bình','1',to_date('03/08/06','DD/MM/RR'),'TP. Hà Nội','0954665978','VATLY','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A432815','Đặng Minh Linh','0',to_date('13/10/04','DD/MM/RR'),'TP. Cần Thơ','0569419951','CNTT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A831603','Lê Minh Quân','1',to_date('06/08/00','DD/MM/RR'),'Q.3, TP.HCM','0868475458','KHKT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A692829','Phan Ngọc Khánh','1',to_date('06/07/01','DD/MM/RR'),'Q.5, TP.HCM','0519614945','TOAN','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A261064','Nguyễn Minh Tú','1',to_date('25/11/01','DD/MM/RR'),'TP. Vũng Tàu','0693310271','SINH','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A307677','Phạm Minh Phúc','0',to_date('11/04/03','DD/MM/RR'),'TP. Vũng Tàu','0190507633','HOA','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A147306','Trần Hữu Vy','0',to_date('29/07/06','DD/MM/RR'),'TP. Đà Nẵng','0662945418','TOAN','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A368784','Lê Văn Nam','1',to_date('16/10/05','DD/MM/RR'),'Q.5, TP.HCM','0804721762','CNTT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A708905','Đặng Thị Dũng','1',to_date('24/07/02','DD/MM/RR'),'TP. Cần Thơ','0161370417','CNTT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A372541','Bùi Ngọc Hương','0',to_date('28/03/04','DD/MM/RR'),'TP. Thủ Đức','0297341115','TOAN','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A626922','Đặng Văn Khánh','0',to_date('10/10/02','DD/MM/RR'),'TP. Thủ Đức','0512769550','KHKT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A759387','Bùi Minh Phúc','1',to_date('05/01/02','DD/MM/RR'),'Q.3, TP.HCM','0720219331','HOA','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A802731','Lê Hữu Châu','0',to_date('02/04/01','DD/MM/RR'),'TP. Cần Thơ','0636548583','SINH','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A133469','Bùi Thị Trang','1',to_date('16/11/05','DD/MM/RR'),'TP. Cần Thơ','0169099456','TOAN','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A356121','Đặng Thị Bình','1',to_date('27/03/01','DD/MM/RR'),'TP. Hà Nội','0990339944','VATLY','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A732898','Phan Anh Khánh','1',to_date('19/05/03','DD/MM/RR'),'TP. Thủ Đức','0740951114','CNTT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A749080','Trần Văn Vy','1',to_date('02/02/06','DD/MM/RR'),'TP. Cần Thơ','0799547129','CNTT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A147741','Hoàng Thị Nam','1',to_date('17/12/01','DD/MM/RR'),'Q.3, TP.HCM','0148068715','CNTT','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A549207','Phan Văn Châu','1',to_date('11/11/05','DD/MM/RR'),'TP. Hà Nội','0584240383','SINH','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A368369','Đặng Anh Bình','1',to_date('25/09/04','DD/MM/RR'),'TP. Vũng Tàu','0783944628','HOA','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A588861','Bùi Gia Trang','0',to_date('02/04/07','DD/MM/RR'),'Q.10, TP.HCM','0159957132','SINH','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A382023','Đặng Anh Nam','0',to_date('27/04/01','DD/MM/RR'),'TP. Cần Thơ','0863414247','SINH','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A240738','Vũ Văn Nam','0',to_date('18/08/02','DD/MM/RR'),'Q.5, TP.HCM','0234249718','KHKT','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A671343','Vũ Thị Khánh','0',to_date('24/02/01','DD/MM/RR'),'Q.5, TP.HCM','0804083979','KHKT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A337530','Phạm Thị Tú','1',to_date('30/11/04','DD/MM/RR'),'Q.3, TP.HCM','0786606149','TOAN','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A599378','Bùi Anh Nam','1',to_date('18/08/04','DD/MM/RR'),'Q.1, TP.HCM','0739486692','KHKT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A786114','Bùi Hữu Tú','1',to_date('09/03/07','DD/MM/RR'),'Q.5, TP.HCM','0364960508','KHKT','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A397998','Phạm Thị Châu','1',to_date('13/02/01','DD/MM/RR'),'TP. Vũng Tàu','0471709937','SINH','Đã tốt nghiệp');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A109069','Trần Hữu Dũng','0',to_date('28/10/06','DD/MM/RR'),'TP. Hà Nội','0611555196','VATLY','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A449077','Bùi Hữu Quân','1',to_date('25/11/03','DD/MM/RR'),'TP. Đà Nẵng','0963187916','SINH','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A673571','Lê Minh Linh','1',to_date('19/11/04','DD/MM/RR'),'TP. Cần Thơ','0173211966','SINH','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A943332','Lê Anh Linh','1',to_date('10/07/06','DD/MM/RR'),'TP. Đà Nẵng','0428547341','HOA','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A305087','Vũ Ngọc Quân','1',to_date('18/12/01','DD/MM/RR'),'Q.3, TP.HCM','0785931547','SINH','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A374851','Bùi Minh Khánh','1',to_date('09/02/07','DD/MM/RR'),'Q.3, TP.HCM','0789864671','SINH','Đã thôi học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A153260','Phan Thị Hương','1',to_date('17/02/03','DD/MM/RR'),'TP. Cần Thơ','0329954891','TOAN','Bảo lưu kết quả học tập');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A878505','Nguyễn Ngọc Bình','1',to_date('24/08/04','DD/MM/RR'),'TP. Vũng Tàu','0166277391','KHKT','Đang học');
Insert into SINHVIEN (MASV,HOTEN,PHAI,NGSINH,DCHI,DT,KHOA,TINHTRANG) values ('A894801','Trần Hữu Phúc','0',to_date('30/09/02','DD/MM/RR'),'TP. Cần Thơ','0385637769','HOA','Đang học');
COMMIT;

--Insert for DANGKY
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A536166', 'MTH00003_1_2024', NULL, NULL, NULL, NULL);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A536166', 'CSC10001_1_2024', NULL, NULL, NULL, NULL);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A864352', 'MTH00003_1_2024', NULL, NULL, NULL, NULL);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A355087', 'MTH00081_1_2024', NULL, NULL, NULL, NULL);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A178637', 'CSC10001_1_2024', NULL, NULL, NULL, NULL);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A536166', 'MTH00003_2_2024', 8.5, 7.0, 7.5, 7.7);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A536166', 'CSC10001_2_2024', 9.0, 8.5, 8.0, 8.3);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A864352', 'MTH00003_2_2024', 7.0, 6.5, 7.0, 6.8);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A864352', 'MTH00081_2_2024', 8.0, 7.5, 8.5, 8.1);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A921624', 'MTH00003_2_2024', 9.5, 9.0, 9.5, 9.3);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A536166', 'MTH00003_3_2024', 7.5, 8.0, 7.0, 7.4);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A475349', 'MTH00003_3_2024', 6.5, 7.0, 5.5, 6.1);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A135403', 'MTH00081_3_2024', 7.5, 8.0, 8.5, 8.1);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A475349', 'CSC10001_2_2024', 3.5, 4.0, 2.0, 2.8);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A110584', 'MTH00003_3_2024', 9.5, 10.0, 9.0, 9.4);
INSERT INTO "DANGKY" (MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK) VALUES ('A921624', 'CSC10001_3_2024', 9.0, 9.5, 10.0, 9.6);
COMMIT;

-- ---------------------------------------------------------
-- Tạo role
-- ---------------------------------------------------------
CREATE ROLE NVCB;
CREATE ROLE GV;
CREATE ROLE NVPDT;
CREATE ROLE NVPKT;
CREATE ROLE NVTCHC;
CREATE ROLE NVPCTSV;
CREATE ROLE TRGDV;
CREATE ROLE SV;

GRANT CREATE SESSION TO NVCB;
GRANT CREATE SESSION TO GV;
GRANT CREATE SESSION TO NVPDT;
GRANT CREATE SESSION TO NVPKT;
GRANT CREATE SESSION TO NVTCHC;
GRANT CREATE SESSION TO NVPCTSV;
GRANT CREATE SESSION TO TRGDV;
GRANT CREATE SESSION TO SV;

-- ---------------------------------------------------------
-- Tạo tài khoản cho nhân viên và sinh viên
-- ---------------------------------------------------------

DECLARE
    v_count NUMBER; -- Biến đếm để kiểm tra sự tồn tại của user
BEGIN
    -- Tạo tài khoản cho nhân viên
    FOR nv IN (SELECT MANLD FROM NHANVIEN) LOOP
        -- Kiểm tra xem username (mã nhân viên) đã tồn tại chưa
        SELECT COUNT(*) INTO v_count 
        FROM all_users 
        WHERE username = nv.MANLD;

        IF v_count = 0 THEN
            -- Tạo user với password là 123
            EXECUTE IMMEDIATE 'CREATE USER "' || nv.MANLD || '" IDENTIFIED BY 123';
            DBMS_OUTPUT.PUT_LINE('Đã tạo tài khoản cho nhân viên ' || nv.MANLD);
        ELSE
            DBMS_OUTPUT.PUT_LINE('Tài khoản ' || nv.MANLD || ' đã tồn tại');
        END IF;
    END LOOP;

    -- Tạo tài khoản cho sinh viên
    FOR sv IN (SELECT MASV FROM SINHVIEN) LOOP
        -- Kiểm tra xem username (mã sinh viên) đã tồn tại chưa
        SELECT COUNT(*) INTO v_count 
        FROM all_users 
        WHERE username = sv.MASV;

        IF v_count = 0 THEN
            -- Tạo user với password là 123
            EXECUTE IMMEDIATE 'CREATE USER "' || sv.MASV || '" IDENTIFIED BY 123';
            -- Gán quyền đọc trên các bảng cần thiết
            DBMS_OUTPUT.PUT_LINE('Đã tạo tài khoản cho sinh viên ' || sv.MASV);
        ELSE
            DBMS_OUTPUT.PUT_LINE('Tài khoản ' || sv.MASV || ' đã tồn tại');
        END IF;
    END LOOP;
END;
/

-- ---------------------------------------------------------
-- Gán role theo vai trò trong bảng NHANVIEN
-- ---------------------------------------------------------
DECLARE
    v_count NUMBER; -- Biến đếm để kiểm tra sự tồn tại của user
BEGIN
    -- Duyệt qua tất cả nhân viên trong bảng NHANVIEN
    FOR nv IN (SELECT MANLD, VAITRO FROM NHANVIEN) LOOP
        -- Kiểm tra xem user (MANLD) có tồn tại không
        SELECT COUNT(*) INTO v_count FROM all_users WHERE username = UPPER(nv.MANLD);

        IF v_count > 0 THEN
            -- Mặc định gán role NVCB cho tất cả vai trò
            EXECUTE IMMEDIATE 'GRANT NVCB TO "' || nv.MANLD || '"';
            -- Gán role tương ứng với VAITRO
            CASE nv.VAITRO
                WHEN 'GV' THEN
                    EXECUTE IMMEDIATE 'GRANT GV TO "' || nv.MANLD || '"';
                    DBMS_OUTPUT.PUT_LINE('Đã gán role GV cho ' || nv.MANLD);
                WHEN 'NVPDT' THEN
                    EXECUTE IMMEDIATE 'GRANT NVPDT TO "' || nv.MANLD || '"';
                    DBMS_OUTPUT.PUT_LINE('Đã gán role NVPDT cho ' || nv.MANLD);
                WHEN 'NVPKT' THEN
                    EXECUTE IMMEDIATE 'GRANT NVPKT TO "' || nv.MANLD || '"';
                    DBMS_OUTPUT.PUT_LINE('Đã gán role NVPKT cho ' || nv.MANLD);
                WHEN 'NVTCHC' THEN
                    EXECUTE IMMEDIATE 'GRANT NVTCHC TO "' || nv.MANLD || '"';
                    DBMS_OUTPUT.PUT_LINE('Đã gán role NVTCHC cho ' || nv.MANLD);
                WHEN 'NVPCTSV' THEN
                    EXECUTE IMMEDIATE 'GRANT NVPCTSV TO "' || nv.MANLD || '"';
                    DBMS_OUTPUT.PUT_LINE('Đã gán role NVPCTSV cho ' || nv.MANLD);
                WHEN 'TRGDV' THEN
                    EXECUTE IMMEDIATE 'GRANT TRGDV TO "' || nv.MANLD || '"';
                    DBMS_OUTPUT.PUT_LINE('Đã gán role TRGDV cho ' || nv.MANLD);
                ELSE
                    -- Mặc định gán role NVCB nếu không khớp với vai trò nào
                    DBMS_OUTPUT.PUT_LINE('Đã gán role NVCB (mặc định) cho ' || nv.MANLD);
            END CASE;
        ELSE
            DBMS_OUTPUT.PUT_LINE('User "' || nv.MANLD || '" không tồn tại, bỏ qua.');
        END IF;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Hoàn thành gán role cho tất cả nhân viên.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Lỗi: ' || SQLERRM);
END;
/


-- ---------------------------------------------------------
-- Gán role SV cho tất cả sinh viên
-- ---------------------------------------------------------
DECLARE
    v_count NUMBER; -- Biến đếm để kiểm tra sự tồn tại của user
BEGIN
    -- Duyệt qua tất cả sinh viên trong bảng SINHVIEN
    FOR sv IN (SELECT MASV FROM SINHVIEN) LOOP
        -- Kiểm tra xem user (MASV) có tồn tại không
        SELECT COUNT(*) INTO v_count FROM all_users WHERE username = UPPER(sv.MASV);

        IF v_count > 0 THEN
            -- Gán role SV
            EXECUTE IMMEDIATE 'GRANT SV TO "' || sv.MASV || '"';
            DBMS_OUTPUT.PUT_LINE('Đã gán role SV cho sinh viên ' || sv.MASV);
        ELSE
            DBMS_OUTPUT.PUT_LINE('User "' || sv.MASV || '" không tồn tại, bỏ qua.');
        END IF;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Hoàn thành gán role SV cho tất cả sinh viên.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Lỗi khi gán role SV: ' || SQLERRM);
END;
/


--===========================================================YC1==================================================
conn sys/123@localhost:1521/PDB as sysdba;
--NV00018: TCHC
--NV00020 : PCTSV --UPDATE LẠI POCLICY SELECT LÀ OKE
--NV00301: NVCB
--------------------------------
-- Câu 1
--------------------------------
-- VAITRO NVCB có quyền SELECT, UPDATE (DT) trên quan hệ NHANVIEN_INFO
CREATE OR REPLACE VIEW NHANVIEN_NVCB AS
SELECT * FROM ADMINPDB.NHANVIEN
WHERE MANLD = SYS_CONTEXT('USERENV','SESSION_USER');

GRANT SELECT, UPDATE (DT) ON NHANVIEN_NVCB TO NVCB;

-- VAITRO TRGDV có quyền SELECT trên quan hệ NHANVIEN_DONVI_INFO trừ LUONG va PHUCAP
CREATE OR REPLACE VIEW NHANVIEN_TRGDV AS
SELECT 
    NV.MANLD, 
    NV.HOTEN, 
    NV.PHAI, 
    NV.NGSINH, 
    NV.DT, 
    NV.VAITRO, 
    NV.MADV,
    CASE 
        WHEN NV.MANLD = SYS_CONTEXT('USERENV','SESSION_USER') THEN NV.LUONG
        ELSE NULL 
    END AS LUONG,
    CASE 
        WHEN NV.MANLD = SYS_CONTEXT('USERENV','SESSION_USER') THEN NV.PHUCAP
        ELSE NULL 
    END AS PHUCAP
FROM ADMINPDB.NHANVIEN NV
WHERE NV.MADV = (SELECT TRG.MADV
                 FROM ADMINPDB.NHANVIEN TRG
                 WHERE TRG.MANLD = SYS_CONTEXT('USERENV','SESSION_USER'));

GRANT SELECT ON NHANVIEN_TRGDV TO TRGDV;


-- VAITRO TCHC có quyền SELECT, INSERT, UPDATE, DELETE trên quan hệ NHANVIEN
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMINPDB.NHANVIEN TO NVTCHC;

--------------------------------
-- Câu 2
--------------------------------
-- VAITRO GV có quyền SELECT trên quan hệ MOMON_INFO
CREATE OR REPLACE VIEW MOMON_GV AS
SELECT * FROM ADMINPDB.MOMON
WHERE MAGV = SYS_CONTEXT('USERENV','SESSION_USER');

GRANT SELECT ON MOMON_GV TO GV;

-- VAITRO NVPDT SELECT, INSERT, UPDATE, DELETE trên quan hệ MOMON
CREATE OR REPLACE VIEW MOMON_PDT AS
SELECT * FROM ADMINPDB.MOMON
WHERE
    (TO_NUMBER(TO_CHAR(SYSDATE, 'MM')) BETWEEN 9 AND 12 AND HK = 1 AND NAM = TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')))
 OR (TO_NUMBER(TO_CHAR(SYSDATE, 'MM')) BETWEEN 1 AND 4 AND HK = 2 AND NAM = TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')) - 1)
 OR (TO_NUMBER(TO_CHAR(SYSDATE, 'MM')) BETWEEN 5 AND 8 AND HK = 3 AND NAM = TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')) - 1);

GRANT SELECT, INSERT, UPDATE, DELETE ON MOMON_PDT TO NVPDT;

-- VAITRO TRGDV có quyền SELECT trên quan hệ MOMON_TRGDV
CREATE OR REPLACE VIEW MOMON_TRGDV AS
SELECT * FROM ADMINPDB.MOMON
WHERE MAGV IN (SELECT NV.MANLD
               FROM ADMINPDB.NHANVIEN NV
               WHERE NV.MADV = (SELECT TRG.MADV
				                FROM ADMINPDB.NHANVIEN TRG
                                WHERE TRG.MANLD = SYS_CONTEXT('USERENV','SESSION_USER')));

GRANT SELECT ON MOMON_TRGDV TO TRGDV;

-- VAITRO SV có quyền SELECT trên quan hệ MOMON_SV
CREATE OR REPLACE VIEW MOMON_SV AS
SELECT * FROM ADMINPDB.MOMON MM
WHERE MM.MAHP IN (SELECT HP.MAHP 
                 FROM ADMINPDB.HOCPHAN HP
                 WHERE HP.MADV = (SELECT SV.KHOA
                                  FROM ADMINPDB.SINHVIEN SV
                                  WHERE SV.MASV = SYS_CONTEXT('USERENV','SESSION_USER')));
                                  
GRANT SELECT ON MOMON_SV TO SV;

--------------------------------
-- CÂU 3
--------------------------------
-- Policy function for SELECT operations on SINHVIEN
CREATE OR REPLACE FUNCTION sinhvien_select_policy (
    p_schema IN VARCHAR2,
    p_object IN VARCHAR2
) RETURN VARCHAR2 
AUTHID CURRENT_USER AS
    v_user VARCHAR2(20) := SYS_CONTEXT('USERENV', 'SESSION_USER');
    v_role VARCHAR2(50);
    v_predicate VARCHAR2(4000);
    v_student_count NUMBER;
BEGIN
    -- Check if user is a student (requires EXEMPT ACCESS POLICY to avoid recursive VPD trigger)
    -- Assuming function runs with privileges to bypass VPD for this check
    SELECT COUNT(*) 
    INTO v_student_count 
    FROM ADMINPDB.SINHVIEN 
    WHERE MASV = v_user;
    
    IF v_student_count > 0 THEN
        -- Students can view their own data
        v_predicate := 'MASV = ''' || v_user || '''';
        RETURN v_predicate;
    END IF;

    -- Check user's role from NHANVIEN
    BEGIN
        SELECT VAITRO 
        INTO v_role 
        FROM ADMINPDB.NHANVIEN 
        WHERE MANLD = v_user;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_role := NULL;
    END;

    IF v_role = 'NVPCTSV' THEN
        -- NV PCTSV can view all SINHVIEN data
        v_predicate := '1=1';
    ELSIF v_role = 'GV' THEN
        -- GV can view SINHVIEN data for their department
        v_predicate := 'KHOA = (SELECT MADV FROM ADMINPDB.NHANVIEN WHERE MANLD = ''' || v_user || ''')';
    ELSE
        -- Deny access for other users (including NVPDT for SELECT, as not specified)
        v_predicate := '1=0';
    END IF;

    RETURN v_predicate;
END;
/

-- Policy function for INSERT, UPDATE, DELETE operations on SINHVIEN
CREATE OR REPLACE FUNCTION sinhvien_modify_policy (
    p_schema IN VARCHAR2,
    p_object IN VARCHAR2
) RETURN VARCHAR2 
AUTHID CURRENT_USER AS
    v_user VARCHAR2(20) := SYS_CONTEXT('USERENV', 'SESSION_USER');
    v_role VARCHAR2(50);
    v_predicate VARCHAR2(4000);
    v_student_count NUMBER;
BEGIN
    -- Check if user is a student (requires EXEMPT ACCESS POLICY to avoid recursive VPD trigger)
    -- Assuming function runs with privileges to bypass VPD for this check
    SELECT COUNT(*) 
    INTO v_student_count 
    FROM ADMINPDB.SINHVIEN 
    WHERE MASV = v_user;
    
    IF v_student_count > 0 THEN
        -- Students can update their own DCHI and DT
        v_predicate := 'MASV = ''' || v_user || '''';
        RETURN v_predicate;
    END IF;

    -- Check user's role from NHANVIEN
    BEGIN
        SELECT VAITRO 
        INTO v_role 
        FROM ADMINPDB.NHANVIEN 
        WHERE MANLD = v_user;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_role := NULL;
    END;

    IF v_role = 'NVPCTSV' THEN
        -- NV PCTSV can modify all SINHVIEN data, but TINHTRANG must be NULL
        v_predicate := 'TINHTRANG IS NULL';
    ELSIF v_role = 'NVPDT' THEN
        -- NV PDT can update TINHTRANG
        v_predicate := '1=1';
    ELSE
        -- Deny modification for other users (including GV)
        v_predicate := '1=0';
    END IF;

    RETURN v_predicate;
END;
/

-- Apply VPD policies to SINHVIEN table
BEGIN
    -- Policy for SELECT
    DBMS_RLS.ADD_POLICY(
        object_schema   => 'ADMINPDB',
        object_name     => 'SINHVIEN',
        policy_name     => 'SINHVIEN_SELECT_POLICY',
        function_schema => 'ADMINPDB',
        policy_function => 'sinhvien_select_policy',
        statement_types  => 'SELECT',
        update_check    => FALSE
    );

    -- Policy for INSERT, UPDATE, DELETE
    DBMS_RLS.ADD_POLICY(
        object_schema   => 'ADMINPDB',
        object_name     => 'SINHVIEN',
        policy_name     => 'SINHVIEN_MODIFY_POLICY',
        function_schema => 'ADMINPDB',
        policy_function => 'sinhvien_modify_policy',
        statement_types  => 'INSERT,UPDATE,DELETE',
        update_check    => TRUE,
        sec_relevant_cols => 'DCHI,DT,TINHTRANG'
    );
END;
/

-- Grant necessary privileges to roles
-- Grant SELECT permission to students (SV)
GRANT SELECT ON ADMINPDB.SINHVIEN TO SV;

-- Grant UPDATE on specific columns (DCHI, DT) to students (SV)
GRANT UPDATE (DCHI, DT) ON ADMINPDB.SINHVIEN TO SV;

-- Grant SELECT, INSERT, UPDATE, DELETE permissions to NVPCTSV
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMINPDB.SINHVIEN TO NVPCTSV;

-- Grant SELECT permission to GV (instructors)
GRANT SELECT ON ADMINPDB.SINHVIEN TO GV;

-- Grant UPDATE permission to NVPDT (academic staff) for updating TINHTRANG
GRANT SELECT, UPDATE (TINHTRANG) ON ADMINPDB.SINHVIEN TO NVPDT;

-- Grant EXEMPT ACCESS POLICY to the user executing the policy functions
-- This ensures the policy function can access SINHVIEN without triggering VPD
GRANT EXEMPT ACCESS POLICY TO ADMINPDB;

--------------------------------
-- CÂU 4
--------------------------------
-- Function to determine semester start date based on HK and NAM
conn ADMINPDB/123@localhost:1521/PDB;
CREATE OR REPLACE FUNCTION get_semester_start_date (
    p_hk NUMBER,
    p_nam NUMBER
) RETURN DATE AS
BEGIN
    CASE p_hk
        WHEN 1 THEN RETURN TO_DATE(TO_CHAR(p_nam) || '-09-01', 'YYYY-MM-DD');
        WHEN 2 THEN RETURN TO_DATE(TO_CHAR(p_nam + 1) || '-01-01', 'YYYY-MM-DD');
        WHEN 3 THEN RETURN TO_DATE(TO_CHAR(p_nam + 1) || '-05-01', 'YYYY-MM-DD');
        ELSE RAISE_APPLICATION_ERROR(-20001, 'Invalid semester (HK)');
    END CASE;
END;
/
conn sys/123@localhost:1521/PDB as sysdba;
GRANT EXECUTE ON adminpdb.get_semester_start_date TO PUBLIC;

-- Policy function for DANGKY table
CREATE OR REPLACE FUNCTION adminpdb.dangky_policy_function (
    p_schema IN VARCHAR2,
    p_object IN VARCHAR2
) RETURN VARCHAR2 
AUTHID CURRENT_USER AS
    v_user VARCHAR2(20) := SYS_CONTEXT('USERENV', 'SESSION_USER');
    v_role VARCHAR2(50);
    v_predicate VARCHAR2(4000);
    v_student_count NUMBER;
BEGIN
    -- Check if user is a student
    SELECT COUNT(*) 
    INTO v_student_count 
    FROM ADMINPDB.SINHVIEN 
    WHERE MASV = v_user;
    
    IF v_student_count > 0 THEN
        -- Students can view their own DANGKY data
        v_predicate := 'MASV = ''' || v_user || '''';
        RETURN v_predicate;
    END IF;

    -- Check user's role from NHANVIEN
    BEGIN
        SELECT VAITRO 
        INTO v_role 
        FROM ADMINPDB.NHANVIEN 
        WHERE MANLD = v_user;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_role := NULL;
    END;

    IF v_role = 'NVPDT' THEN
        -- NVPDT can view DANGKY for MOMON within 14 days of semester start
        v_predicate := 'MAMM IN (SELECT MAMM FROM ADMINPDB.MOMON_PDT WHERE SYSDATE <= adminpdb.get_semester_start_date(HK, NAM) + 40)';
    ELSIF v_role = 'NVPKT' THEN
        -- NV PKT can view all DANGKY data
        v_predicate := '1=1';
    ELSIF v_role = 'GV' THEN
        -- GV can view DANGKY for classes they teach (via MOMON.MAGV)
        v_predicate := 'MAMM IN (SELECT MAMM FROM ADMINPDB.MOMON_GV WHERE MAGV = ''' || v_user || ''')';
    ELSE
        -- Deny access for other users
        v_predicate := '1=0';
    END IF;

    RETURN v_predicate;
END;
/

BEGIN
    DBMS_RLS.ADD_POLICY (
        object_schema   => 'ADMINPDB',
        object_name     => 'DANGKY',
        policy_name     => 'DANGKY_SELECT_POLICY',
        function_schema => 'ADMINPDB',
        policy_function => 'dangky_policy_function',
        statement_types => 'SELECT',
        update_check    => FALSE
    );
END;
/

-- Policy function for INSERT, UPDATE, DELETE operations on DANGKY
CREATE OR REPLACE FUNCTION adminpdb.dangky_modify_policy (
    p_schema IN VARCHAR2,
    p_object IN VARCHAR2
) RETURN VARCHAR2 
AUTHID CURRENT_USER AS
    v_user VARCHAR2(20) := SYS_CONTEXT('USERENV', 'SESSION_USER');
    v_role VARCHAR2(50);
    v_predicate VARCHAR2(4000);
    v_student_count NUMBER;
BEGIN
    -- Check if user is a student
    SELECT COUNT(*) 
    INTO v_student_count 
    FROM ADMINPDB.SINHVIEN 
    WHERE MASV = v_user;
    
    IF v_student_count > 0 THEN
        -- Students can modify their own DANGKY records within 14 days of semester start, where grades are NULL
        v_predicate := 'MASV = ''' || v_user || ''' AND MAMM IN (SELECT MAMM FROM ADMINPDB.MOMON_SV WHERE SYSDATE <= adminpdb.get_semester_start_date(HK, NAM) + 40) AND DIEMTH IS NULL AND DIEMQT IS NULL AND DIEMCK IS NULL AND DIEMTK IS NULL';
        RETURN v_predicate;
    END IF;

    -- Check user's role from NHANVIEN
    BEGIN
        SELECT VAITRO 
        INTO v_role 
        FROM ADMINPDB.NHANVIEN 
        WHERE MANLD = v_user;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_role := NULL;
    END;

    IF v_role = 'NVPDT' THEN
        -- NV PĐT can modify DANGKY for MOMON within 14 days of semester start, where grades are NULL
        v_predicate := 'MAMM IN (SELECT MAMM FROM ADMINPDB.MOMON_PDT WHERE SYSDATE <= adminpdb.get_semester_start_date(HK, NAM) + 40) AND DIEMTH IS NULL AND DIEMQT IS NULL AND DIEMCK IS NULL AND DIEMTK IS NULL';
    ELSIF v_role = 'NVPKT' THEN
        -- NV PKT can update grade fields (no restriction on time or grades)
        v_predicate := '1=1';
    ELSE
        -- Deny modification for other users
        v_predicate := '1=0';
    END IF;

    RETURN v_predicate;
END;
/

-- Apply VPD policies to DANGKY table
BEGIN
    -- Policy for INSERT, UPDATE, DELETE
    DBMS_RLS.ADD_POLICY(
        object_schema   => 'ADMINPDB',
        object_name     => 'DANGKY',
        policy_name     => 'DANGKY_MODIFY_POLICY',
        function_schema => 'ADMINPDB',
        policy_function => 'dangky_modify_policy',
        statement_types  => 'INSERT,UPDATE,DELETE',
        update_check    => TRUE
    );
END;
/

-- Cấp quyền cho sinh viên (SV)
GRANT SELECT, INSERT, UPDATE ON ADMINPDB.DANGKY TO SV;

-- Cấp quyền cho nhân viên phòng đào tạo (NVPDT)
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMINPDB.DANGKY TO NVPDT;

-- Cấp quyền cho nhân viên phòng khảo thí (NVPKT)
GRANT SELECT, UPDATE ON ADMINPDB.DANGKY TO NVPKT;

-- Cấp quyền cho giảng viên (GV)
GRANT SELECT ON ADMINPDB.DANGKY TO GV;

----------------------------
-- Addition procedure to get MetaData
----------------------------
-- Force to delete Dangky (and also delete Momon to ensure consistency) for NVPDT
GRANT EXECUTE ON DBMS_RLS TO ADMINPDB;

conn AdminPdb/123@localhost:1521/PDB;

CREATE OR REPLACE PROCEDURE force_delete_dangky_and_momon(p_mamm VARCHAR2)
AUTHID DEFINER
IS
BEGIN
    -- Tạm tắt VPD policy
    DBMS_RLS.ENABLE_POLICY(
        object_schema  => 'ADMINPDB',
        object_name    => 'DANGKY',
        policy_name    => 'DANGKY_MODIFY_POLICY',
        enable         => FALSE
    );

    DELETE FROM ADMINPDB.DANGKY
    WHERE MAMM = p_mamm;
    
    DELETE FROM ADMINPDB.MOMON
    WHERE MAMM = p_mamm;

    -- Bật lại VPD policy
    DBMS_RLS.ENABLE_POLICY(
        object_schema  => 'ADMINPDB',
        object_name    => 'DANGKY',
        policy_name    => 'DANGKY_MODIFY_POLICY',
        enable         => TRUE
    );
END;
/

GRANT EXECUTE ON ADMINPDB.force_delete_dangky_and_momon TO NVPDT;

CREATE OR REPLACE PROCEDURE get_modules(p_result OUT SYS_REFCURSOR) AUTHID DEFINER IS
BEGIN
  OPEN p_result FOR
    SELECT MAHP, TENHP FROM adminpdb.HOCPHAN;
END;
/

-- Procedure to get instructors
CREATE OR REPLACE PROCEDURE get_instructors(p_result OUT SYS_REFCURSOR) AUTHID DEFINER IS
BEGIN
  OPEN p_result FOR
    SELECT MANLD, HOTEN FROM adminpdb.NHANVIEN WHERE VAITRO = 'GV';
END;
/

GRANT EXECUTE ON ADMINPDB.get_modules TO NVPDT;
GRANT EXECUTE ON ADMINPDB.get_instructors TO NVPDT;



-- 1. Connect as SYS and prepare environment
CONNECT sys/123@localhost:1521/PDB AS SYSDBA;
@?/rdbms/admin/catols.sql


-- Enable OLS if not already done
EXEC LBACSYS.CONFIGURE_OLS;
COMMIT;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
COMMIT;
-- 2. Clean up existing setup (if any)
DROP USER ols_admin CASCADE;

-- Drop existing users U1-U8 if they exist
DECLARE
  v_sql VARCHAR2(200);
BEGIN
  FOR i IN 1..8 LOOP
    BEGIN
      v_sql := 'DROP USER U' || i || ' CASCADE';
      EXECUTE IMMEDIATE v_sql;
      DBMS_OUTPUT.PUT_LINE('Dropped user U' || i);
    EXCEPTION
      WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('User U' || i || ' does not exist or error: ' || SQLERRM);
    END;
  END LOOP;
END;
/

-- 3. Create OLS admin account with proper privileges
CREATE USER ols_admin IDENTIFIED BY 123;
GRANT UNLIMITED TABLESPACE TO ols_admin;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE TRIGGER TO ols_admin;
GRANT LBAC_DBA TO ols_admin;
GRANT EXECUTE ON sa_components TO ols_admin;
GRANT EXECUTE ON sa_label_admin TO ols_admin;
GRANT EXECUTE ON sa_policy_admin TO ols_admin;
GRANT EXECUTE ON sa_user_admin TO ols_admin;
GRANT EXECUTE ON sa_sysdba TO ols_admin;
GRANT EXECUTE ON sa_session TO ols_admin;
GRANT ADMINISTER DATABASE TRIGGER TO ols_admin;

-- 4. Create test users (U1-U8)
BEGIN
  FOR i IN 1..8 LOOP
    EXECUTE IMMEDIATE 'CREATE USER U' || i || ' IDENTIFIED BY 123';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO U' || i;
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.SA_SESSION TO U' || i;
    DBMS_OUTPUT.PUT_LINE('Created user U' || i);
  END LOOP;
END;
/

-- 5. Connect as OLS_ADMIN and create policy components
CONNECT ols_admin/123@localhost:1521/PDB;

-- Drop existing policy if exists
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE THONGBAO CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN

  SA_SYSDBA.DROP_POLICY('THONGBAO_POLICY');
END;
/


-- Create new policy
CONNECT ols_admin/123@localhost:1521/PDB;

BEGIN
  SA_SYSDBA.CREATE_POLICY(
    policy_name     => 'THONGBAO_POLICY',
    column_name     => 'OLS_LABEL',
    default_options => 'NO_CONTROL'
  );
END;
/

CONNECT ols_admin/123@localhost:1521/PDB;

-- 6. Create security components
BEGIN
  -- Levels (hierarchical: TRGDV > NV > SV)
  SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY', 100, 'SV', 'Sinh viên');
  SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY', 200, 'NV', 'Nhân viên');  
  SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY', 300, 'TRGDV', 'Trưởng đơn vị');
  
  -- Compartments (departments)
  SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY', 10, 'TOAN', 'Toán');
  SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY', 20, 'LY', 'Lý');
  SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY', 30, 'HOA', 'Hóa');
  SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY', 40, 'TCHC', 'Hành chính');
  
  -- Groups (locations)
  SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY', 1, 'CS1', 'Cơ sở 1');
  SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY', 2, 'CS2', 'Cơ sở 2');
  
  END;
/

CONN ols_admin/123@localhost:1521/PDB;

-- 7. Create and populate THONGBAO table

CREATE TABLE THONGBAO (
  MATB      VARCHAR2(10) PRIMARY KEY,
  TIEUDE    VARCHAR2(100) NOT NULL,
  NOIDUNG   VARCHAR2(4000) NOT NULL,
  NGAYTB    DATE DEFAULT SYSDATE,
  OLS_LABEL NUMBER
);

INSERT INTO THONGBAO (MATB, TIEUDE, NOIDUNG) VALUES 
('T1', 'Hop toan truong', 'Moi tat ca truong don vi hop');
INSERT INTO THONGBAO (MATB, TIEUDE, NOIDUNG) VALUES 
('T2', 'Thong bao chung', 'Thay doi gio lam viec cho nhan vien');
INSERT INTO THONGBAO (MATB, TIEUDE, NOIDUNG) VALUES 
('T3', 'Lich thi hoc ky', 'Lich thi hoc ky 2 cho sinh vien');
INSERT INTO THONGBAO (MATB, TIEUDE, NOIDUNG) VALUES 
('T4', 'Thong bao khoa hoa CS1', 'Lich thuc hanh hoa hoc CS1');
INSERT INTO THONGBAO (MATB, TIEUDE, NOIDUNG) VALUES 
('T5', 'Thong bao khoa hoa CS2', 'Phong thi nghiem moi CS2');
INSERT INTO THONGBAO (MATB, TIEUDE, NOIDUNG) VALUES 
('T6', 'Hoi thao khoa hoc hoa', 'Hoi thao ngay 15/5 khoa Hoa');
INSERT INTO THONGBAO (MATB, TIEUDE, NOIDUNG) VALUES 
('T7', 'Le tot nghiep', 'Thong tin le tot nghiep cho SV');
INSERT INTO THONGBAO (MATB, TIEUDE, NOIDUNG) VALUES 
('T8', 'Hop truong khoa hoa CS1', 'Ke hoach nam hoc khoa Hoa CS1');
INSERT INTO THONGBAO (MATB, TIEUDE, NOIDUNG) VALUES 
('T9', 'Danh gia chat luong hoa', 'Bao cao chat luong khoa Hoa');
BEGIN
  -- Label cho trưởng đơn vị
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 1000, 'TRGDV');
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 1010, 'TRGDV:HOA');
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 1020, 'TRGDV:HOA:CS1');
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 1030, 'TRGDV:HOA:CS2');
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 1040, 'TRGDV:LY:CS2');
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 1050, 'TRGDV:TCHC');
  
  -- Label cho nhân viên
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 2000, 'NV');
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 2010, 'NV:HOA:CS2');
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 2020, 'NV:TCHC:CS1');
  
  -- Label cho sinh viên
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 3000, 'SV');
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 3010, 'SV:HOA:CS1');
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 3020, 'SV:HOA:CS2');
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 3030, 'SV:HOA');
END;
/

-- 8. Apply policy to table (READ_CONTROL first)
BEGIN
  SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    policy_name   => 'THONGBAO_POLICY',
    schema_name   => 'OLS_ADMIN',
    table_name    => 'THONGBAO',
    table_options => 'READ_CONTROL'
  );
  -- DBMS_OUTPUT.PUT_LINE('Applied READ_CONTROL to table');
END;
/

conn SYS/123@localhost:1521/PDB AS SYSDBA;
-- 9. Set labels for notifications
UPDATE OLS_ADMIN.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('THONGBAO_POLICY', 'TRGDV') WHERE MATB = 'T1';
UPDATE OLS_ADMIN.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('THONGBAO_POLICY', 'NV') WHERE MATB = 'T2';
UPDATE OLS_ADMIN.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('THONGBAO_POLICY', 'SV') WHERE MATB = 'T3';
UPDATE OLS_ADMIN.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('THONGBAO_POLICY', 'SV:HOA:CS1') WHERE MATB = 'T4';
UPDATE OLS_ADMIN.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('THONGBAO_POLICY', 'SV:HOA:CS2') WHERE MATB = 'T5';
UPDATE OLS_ADMIN.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('THONGBAO_POLICY', 'SV:HOA') WHERE MATB = 'T6';
UPDATE OLS_ADMIN.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('THONGBAO_POLICY', 'SV') WHERE MATB = 'T7';
UPDATE OLS_ADMIN.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('THONGBAO_POLICY', 'TRGDV:HOA:CS1') WHERE MATB = 'T8';
UPDATE OLS_ADMIN.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('THONGBAO_POLICY', 'TRGDV:HOA') WHERE MATB = 'T9';


conn OLS_ADMIN/123@localhost:1521/PDB;
-- 10. Set user labels (authorization)
BEGIN
  -- U1: Trưởng đơn vị toàn quyền
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U1', 'TRGDV:TOAN,LY,HOA,TCHC:CS1,CS2');
  
  -- U2: Trưởng khoa Hóa CS2
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U2', 'TRGDV:HOA:CS2');
  
  -- U3: Trưởng khoa Lý CS2
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U3', 'TRGDV:LY:CS2');
  
  -- U4: Nhân viên Hóa CS2
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U4', 'NV:HOA:CS2');
  
  -- U5: Sinh viên Hóa CS2
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U5', 'SV:HOA:CS2');
  
  -- U6: Trưởng đơn vị hành chính
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U6', 'TRGDV:TCHC:CS1,CS2');
  
  -- U7: Nhân viên toàn quyền
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U7', 'NV:TOAN,LY,HOA,TCHC:CS1,CS2');
  
  -- U8: Nhân viên hành chính CS1
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_POLICY', 'U8', 'NV:TCHC:CS1');
  
  COMMIT;
END;
/
-- 11. Apply full policy enforcement
BEGIN
  SA_POLICY_ADMIN.REMOVE_TABLE_POLICY(
    policy_name   => 'THONGBAO_POLICY',
    schema_name   => 'OLS_ADMIN', 
    table_name    => 'THONGBAO',
    drop_column   => FALSE
  );
  
  SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    policy_name   => 'THONGBAO_POLICY',
    schema_name   => 'OLS_ADMIN',
    table_name    => 'THONGBAO', 
    table_options => 'READ_CONTROL,WRITE_CONTROL,CHECK_CONTROL'
  );
  
  -- DBMS_OUTPUT.PUT_LINE('Applied full policy enforcement');
END;
/

-- 12. Enable and subscribe policy
BEGIN
  SA_SYSDBA.ALTER_POLICY(
    policy_name     => 'THONGBAO_POLICY',
    default_options => 'READ_CONTROL,WRITE_CONTROL,CHECK_CONTROL'
  );
  
  SA_SYSDBA.ENABLE_POLICY('THONGBAO_POLICY');
  -- DBMS_OUTPUT.PUT_LINE('Policy enabled and subscribed');
END;
/

-- Grant SELECT permission to all test users
GRANT SELECT ON THONGBAO TO U1,U2,U3,U4,U5,U6,U7,U8;



conn U6/123@localhost:1521/PDB;
select MATB from ols_admin.THONGBAO;



QUIT;
