LOAD DATA
CHARACTERSET AL32UTF8
INFILE 'data_sinhvien_4000.csv'
INTO TABLE SYSTEM.SINHVIEN
APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  MASV,
  HOTEN,
  PHAI,
  NGSINH DATE "YYYY-MM-DD",
  DCHI,
  DT,
  KHOA,
  TINHTRANG
)
